/**
 * PurchaseService — the payment state machine (SYSTEM_ARCHITECTURE §6). Payment
 * and purchase status transitions exist ONLY here; SubscriptionService composes
 * the same primitives (beginAttempt / runProvider / finalize*) rather than
 * touching payment state itself.
 *
 * Shape of every paid flow:
 *   TX1  validate + insert payment(pending) & purchase(pending)   — commits
 *   ...  provider phases run OUTSIDE any transaction (network I/O)
 *   TX2  finalize: mark rows, write audit IN-TX, raise events     — commits,
 *        then events dispatch (strictly after commit, ADR-010)
 * A crash between TX1 and TX2 leaves a pending pair for the cleanup job (M5).
 * The unique payments.idempotency_key absorbs double-taps: a replayed key
 * returns the original attempt's outcome instead of charging twice.
 */
import { appError, type AppError } from '../../shared/app-error.js';
import { err, ok, type Result } from '../../shared/result.js';
import type { AccessGrant, Payment, Purchase } from '../../shared/entities.js';
import type { DropId, PlanId, Stars, UserId } from '../../shared/domain.js';
import type { EventBuffer } from '../events/dispatcher.js';
import type { Clock } from '../ports/clock.port.js';
import type {
  PaymentConfirmation,
  PaymentProvider,
  PaymentRequest,
} from '../ports/payment-provider.port.js';
import type { Repositories, UnitOfWork } from '../repositories/index.js';
import { AccessService } from './access.service.js';
import { AuditService } from './audit.service.js';
import { CreatorService } from './creator.service.js';

export interface PurchaseDropInput {
  readonly userId: UserId;
  readonly dropId: DropId;
  /** Generated by the client per logical attempt; a retry after failure needs a new key. */
  readonly idempotencyKey: string;
  readonly correlationId?: string;
}

export interface PurchaseOutcome {
  readonly payment: Payment;
  readonly purchase: Purchase;
  readonly grant: AccessGrant | null;
}

/** What a replayed idempotency key resolves to. */
export type Replay =
  | { readonly kind: 'none' }
  | { readonly kind: 'completed'; readonly payment: Payment; readonly purchase: Purchase }
  | { readonly kind: 'failed'; readonly payment: Payment; readonly purchase: Purchase }
  | { readonly kind: 'in_flight'; readonly payment: Payment; readonly purchase: Purchase };

interface BeginAttemptTarget {
  readonly userId: UserId;
  readonly creatorId: string;
  readonly dropId?: DropId | null;
  readonly planId?: PlanId | null;
  readonly amountStars: Stars;
  readonly idempotencyKey: string;
}

interface FinalizeContext {
  readonly payment: Payment;
  readonly purchase: Purchase;
  readonly correlationId?: string;
}

export class PurchaseService {
  constructor(
    private readonly uow: UnitOfWork,
    private readonly provider: PaymentProvider,
    private readonly access: AccessService,
    private readonly audit: AuditService,
    private readonly clock: Clock,
  ) {}

  async purchaseDrop(input: PurchaseDropInput): Promise<Result<PurchaseOutcome, AppError>> {
    type Setup =
      | { kind: 'error'; error: AppError }
      | { kind: 'replay'; replay: Exclude<Replay, { kind: 'none' }> }
      | { kind: 'fresh'; payment: Payment; purchase: Purchase; dropTitle: string };

    const setup = await this.uow.run(async (repos): Promise<Setup> => {
      const replay = await this.resolveReplay(repos, input.idempotencyKey);
      if (replay.kind !== 'none') {
        if (replay.purchase.dropId !== input.dropId) {
          return {
            kind: 'error',
            error: appError('conflict', 'This payment reference was used for something else.', {
              idempotencyKey: input.idempotencyKey,
            }),
          };
        }
        return { kind: 'replay', replay };
      }

      const decision = await this.access.canAccess(repos, input.userId, input.dropId);
      if (decision.allowed) {
        return {
          kind: 'error',
          error: appError('already_owned', 'You already have access to this content.', {
            dropId: input.dropId,
            basis: decision.basis,
          }),
        };
      }
      if (decision.drop === null) {
        return {
          kind: 'error',
          error: appError('not_found', 'Drop not found.', { dropId: input.dropId }),
        };
      }
      const drop = decision.drop;
      if (drop.accessType !== 'pay_per_unlock' || drop.priceStars === null) {
        return {
          kind: 'error',
          error: appError('validation', 'This content is not sold per unlock.', {
            dropId: drop.id,
            accessType: drop.accessType,
          }),
        };
      }
      const creator = await CreatorService.requireActive(repos, drop.creatorId);
      if (!creator.ok) return { kind: 'error', error: creator.error };
      const user = await repos.users.findById(input.userId);
      if (user === null) {
        return {
          kind: 'error',
          error: appError('not_found', 'User not found.', { userId: input.userId }),
        };
      }

      const attempt = await this.beginAttempt(repos, {
        userId: input.userId,
        creatorId: drop.creatorId,
        dropId: drop.id,
        amountStars: drop.priceStars,
        idempotencyKey: input.idempotencyKey,
      });
      return { kind: 'fresh', ...attempt, dropTitle: drop.title };
    });

    if (setup.kind === 'error') return err(setup.error);
    if (setup.kind === 'replay') return this.replayedDropOutcome(setup.replay);

    const confirmation = await this.runProvider({
      idempotencyKey: input.idempotencyKey,
      amountStars: setup.payment.amountStars,
      description: `Unlock "${setup.dropTitle}"`,
      userId: input.userId,
      creatorId: setup.payment.creatorId,
    });

    if (confirmation.status === 'failed') {
      await this.uow.run(async (repos, events) => {
        await this.finalizeFailure(repos, events, {
          payment: setup.payment,
          purchase: setup.purchase,
          correlationId: input.correlationId,
          reason: confirmation.reason,
          rawPayload: confirmation.rawPayload ?? { reason: confirmation.reason },
        });
      });
      return err(
        appError(
          'payment_failed',
          'Payment failed — you have not been charged. Please try again.',
          {
            reason: confirmation.reason,
          },
        ),
      );
    }

    return this.uow.run(async (repos, events) => {
      const finalized = await this.finalizeSuccess(repos, events, {
        payment: setup.payment,
        purchase: setup.purchase,
        correlationId: input.correlationId,
        confirmation,
      });
      const grant = await repos.accessGrants.create({
        userId: input.userId,
        dropId: input.dropId,
        creatorId: finalized.payment.creatorId,
        grantType: 'purchase',
        sourcePurchaseId: finalized.purchase.id,
      });
      await this.audit.record(repos, {
        creatorId: grant.creatorId,
        action: 'grant.created',
        entityType: 'access_grant',
        entityId: grant.id,
        actorType: 'user',
        actorUserId: input.userId,
        correlationId: input.correlationId,
        context: { dropId: input.dropId, sourcePurchaseId: finalized.purchase.id },
      });
      // ContentUnlocked is NOT raised here — DeliveryEngine emits it after the
      // content is actually delivered (ADR-019 ruling).
      return ok({ ...finalized, grant });
    });
  }

  async listUserPurchases(userId: UserId): Promise<Purchase[]> {
    return this.uow.run(async (repos) => repos.purchases.listByUser(userId));
  }

  // ---- primitives shared with SubscriptionService (state transitions live here only) ----

  /** Resolve an idempotency key to its prior attempt, if any. */
  async resolveReplay(repos: Repositories, idempotencyKey: string): Promise<Replay> {
    const payment = await repos.payments.findByIdempotencyKey(idempotencyKey);
    if (payment === null) return { kind: 'none' };
    const purchase = await repos.purchases.findByPaymentId(payment.id);
    if (purchase === null) {
      // payments and purchases are created in the same transaction — a lone payment is a bug
      throw new Error(`payment ${payment.id} has no purchase row`);
    }
    switch (payment.status) {
      case 'succeeded':
        return { kind: 'completed', payment, purchase };
      case 'failed':
        return { kind: 'failed', payment, purchase };
      default:
        return { kind: 'in_flight', payment, purchase };
    }
  }

  /** TX1 half: insert the pending payment + purchase pair. */
  async beginAttempt(
    repos: Repositories,
    target: BeginAttemptTarget,
  ): Promise<{ payment: Payment; purchase: Purchase }> {
    const payment = await repos.payments.create({
      creatorId: target.creatorId,
      provider: this.provider.name,
      idempotencyKey: target.idempotencyKey,
      amountStars: target.amountStars,
      status: 'pending',
    });
    const purchase = await repos.purchases.create({
      userId: target.userId,
      creatorId: target.creatorId,
      dropId: target.dropId ?? null,
      planId: target.planId ?? null,
      paymentId: payment.id,
      amountStars: target.amountStars,
      status: 'pending',
    });
    return { payment, purchase };
  }

  /** Provider phases (ADR-005 lifecycle) — outside any transaction. */
  async runProvider(request: PaymentRequest): Promise<PaymentConfirmation> {
    const intent = await this.provider.createIntent(request);
    const approval = await this.provider.awaitApproval(intent);
    if (!approval.approved) {
      return { status: 'failed', reason: approval.reason };
    }
    return this.provider.confirm(intent);
  }

  /** TX2, success branch: pending → succeeded/completed + audit + PurchaseCompleted. */
  async finalizeSuccess(
    repos: Repositories,
    events: EventBuffer,
    ctx: FinalizeContext & { confirmation: Extract<PaymentConfirmation, { status: 'succeeded' }> },
  ): Promise<{ payment: Payment; purchase: Purchase }> {
    const payment = await repos.payments.markSucceeded(
      ctx.payment.id,
      ctx.confirmation.providerChargeId,
      ctx.confirmation.rawPayload ?? null,
    );
    const purchase = await repos.purchases.markCompleted(ctx.purchase.id);
    await this.audit.record(repos, {
      creatorId: payment.creatorId,
      action: 'payment.succeeded',
      entityType: 'payment',
      entityId: payment.id,
      actorType: 'user',
      actorUserId: purchase.userId,
      correlationId: ctx.correlationId,
      context: { amountStars: payment.amountStars, provider: payment.provider },
    });
    await this.audit.record(repos, {
      creatorId: purchase.creatorId,
      action: 'purchase.completed',
      entityType: 'purchase',
      entityId: purchase.id,
      actorType: 'user',
      actorUserId: purchase.userId,
      correlationId: ctx.correlationId,
      context: {
        amountStars: purchase.amountStars,
        dropId: purchase.dropId,
        planId: purchase.planId,
      },
    });
    events.raise({
      type: 'PurchaseCompleted',
      purchaseId: purchase.id,
      userId: purchase.userId,
      creatorId: purchase.creatorId,
      dropId: purchase.dropId,
      planId: purchase.planId,
      amountStars: purchase.amountStars,
      occurredAt: this.clock.now(),
    });
    return { payment, purchase };
  }

  /** TX2, failure branch: pending → failed/failed + audit + PaymentFailed. */
  async finalizeFailure(
    repos: Repositories,
    events: EventBuffer,
    ctx: FinalizeContext & { reason: string; rawPayload: unknown },
  ): Promise<void> {
    const payment = await repos.payments.markFailed(ctx.payment.id, ctx.rawPayload);
    const purchase = await repos.purchases.markFailed(ctx.purchase.id);
    await this.audit.record(repos, {
      creatorId: payment.creatorId,
      action: 'payment.failed',
      entityType: 'payment',
      entityId: payment.id,
      actorType: 'user',
      actorUserId: purchase.userId,
      correlationId: ctx.correlationId,
      context: { amountStars: payment.amountStars, provider: payment.provider, reason: ctx.reason },
    });
    await this.audit.record(repos, {
      creatorId: purchase.creatorId,
      action: 'purchase.failed',
      entityType: 'purchase',
      entityId: purchase.id,
      actorType: 'user',
      actorUserId: purchase.userId,
      correlationId: ctx.correlationId,
      context: { reason: ctx.reason },
    });
    events.raise({
      type: 'PaymentFailed',
      paymentId: payment.id,
      purchaseId: purchase.id,
      userId: purchase.userId,
      creatorId: purchase.creatorId,
      amountStars: payment.amountStars,
      reason: ctx.reason,
      occurredAt: this.clock.now(),
    });
  }

  /** A replayed key returns the original attempt's outcome — never a second charge. */
  private async replayedDropOutcome(
    replay: Exclude<Replay, { kind: 'none' }>,
  ): Promise<Result<PurchaseOutcome, AppError>> {
    switch (replay.kind) {
      case 'completed': {
        const grant = await this.uow.run(async (repos) =>
          replay.purchase.dropId === null
            ? null
            : repos.accessGrants.findLiveGrant(replay.purchase.userId, replay.purchase.dropId),
        );
        return ok({ payment: replay.payment, purchase: replay.purchase, grant });
      }
      case 'failed':
        return err(
          appError(
            'payment_failed',
            'Payment failed — you have not been charged. Please try again.',
            {
              replayed: true,
            },
          ),
        );
      case 'in_flight':
        return err(
          appError('conflict', 'This payment is already being processed.', {
            paymentId: replay.payment.id,
          }),
        );
    }
  }
}
